services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: lphenom-media-dev
    volumes:
      - .:/app
      - vendor_cache:/app/vendor
    working_dir: /app
    environment:
      - COMPOSER_HOME=/tmp/composer

volumes:
  vendor_cache:

